# Generated by Django 5.2.2 on 2025-12-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(blank=True, help_text='AI matching score (0.0-5.0)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills_extracted',
            field=models.JSONField(blank=True, help_text='Skills extracted from CV', null=True),
        ),
    ]
