# Generated by Django 5.2.2 on 2025-10-31 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads_a', to=settings.AUTH_USER_MODEL)),
                ('participant_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_threads',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.chatthread')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='EmployerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_rating', models.PositiveSmallIntegerField(default=0)),
                ('salary_rating', models.PositiveSmallIntegerField(default=0)),
                ('process_rating', models.PositiveSmallIntegerField(default=0)),
                ('overall_rating', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employer_reviews',
            },
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['participant_a'], name='chat_thread_partici_4165d2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['participant_b'], name='chat_thread_partici_5b72d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatthread',
            unique_together={('participant_a', 'participant_b')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread'], name='chat_messag_thread__0576a0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chat_messag_created_eb4133_idx'),
        ),
        migrations.AddIndex(
            model_name='employerreview',
            index=models.Index(fields=['employer'], name='employer_re_employe_862ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='employerreview',
            index=models.Index(fields=['reviewer'], name='employer_re_reviewe_6cb4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='employerreview',
            index=models.Index(fields=['overall_rating'], name='employer_re_overall_88b93c_idx'),
        ),
        migrations.AddIndex(
            model_name='employerreview',
            index=models.Index(fields=['verified'], name='employer_re_verifie_91f1c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employerreview',
            unique_together={('employer', 'reviewer')},
        ),
    ]
